env:
    #credentials: "ENCRYPTED[4526be3acf95a0d69e63c2024f61eacc9becd1b166eb4c671a0f62030a7927284dab21b9a07ba52c425948ff430e8727]"
    rcloneconfig: "ENCRYPTED[!390d791dd32ae0cc42171f088429ceada42eeb11f9944728b33bfa206d45fd69488c8bb6770613806af5c34d0573becd!]"
    tokentl: "ENCRYPTED[!61abce6a505144c849b5aeff0f386ff5e305f7e6ec0ecc10c8f6b8f7df2a2aa75026dac72f322fb471f66cc8c0e360a8!]"
    idtl: "ENCRYPTED[!0471e8c4263c8fe122aa4bf50f3320c998ee0449343e74d8fb7df2ae7635128a9163aff08fa4bb0175c75ca662b7d865!]"
    lunch: lunch calyx_sweet-user
    make: m

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       #- curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       #- mkdir -p ~/.config/rclone
    #   - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "phoenix8870"
       - git config --global user.email "harigphotos1708@gmail.com"
       - git config --global color.ui true
      # - git lfs install
       - git clone https://huggingface.co/spaces/phoenix-1708/stable-diffusion-webui-cpu
       - cd stable-diffusion-webui-cpu
       - python app.py
